version: 2.1
jobs:
  lint:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: cp providers.tf.example providers.tf
      - run: terraform-0.12.29 init
      - run: terraform-0.12.29 fmt -check=true
      - run: terraform-0.12.29 validate -var "deployment_id=validate" -var "route53_domain=validate-fake.com" -var "admin_email=fake@mailinator.com"
      - run: |
            for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cp providers.tf $example
            cd $example
            echo $example
            terraform-0.12.29 init
            terraform-0.12.29 fmt -check=true
            terraform-0.12.29 validate -var "deployment_id=citest"
            cd -
            done
      - run: terraform-0.12.29 -v
  # from_scratch:
  #   docker:
  #     - image: quay.io/astronomer/ci-terraform:2020-12
  #   steps:
  # from_scratch_cleanup:
  #   docker:
  #     - image: quay.io/astronomer/ci-terraform:2020-12
  #   steps:
  # git_tag:
  # slack:
  # slack_tag:

workflows:
  test_pipeline:
    jobs:
      - lint