version: 2.1
jobs:
  lint:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: cp providers.tf.example providers.tf
      - run: terraform-0.12.29 init
      - run: terraform-0.12.29 fmt -check=true
      - run: terraform-0.12.29 validate -var "deployment_id=validate" -var "route53_domain=validate-fake.com" -var "admin_email=fake@mailinator.com"
      - run: |
            for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cp providers.tf $example
            cd $example
            echo $example
            terraform-0.12.29 init
            terraform-0.12.29 fmt -check=true
            terraform-0.12.29 validate -var "deployment_id=citest"
            cd -
            done
      - run: terraform-0.12.29 -v
  apply:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            mv ./aws-iam-authenticator /usr/local/bin/
            which aws-iam-authenticator
      - run: EXAMPLE=from_scratch pipeline/run_terraform.sh
  destroy:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: DESTROY=1 EXAMPLE=from_scratch pipeline/run_terraform.sh
  # git_tag:
  # slack:
  # slack_tag:

workflows:
  test_pipeline:
    jobs:
      - lint
      - apply:
          requires:
            - lint
      - destroy:
          requires:
            - apply
      