version: 2.1
jobs:
  lint:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: echo "this is the build job"
  # from_scratch:
  #   docker:
  #     - image: quay.io/astronomer/ci-terraform:2020-12
  #   steps:
  # from_scratch_cleanup:
  #   docker:
  #     - image: quay.io/astronomer/ci-terraform:2020-12
  #   steps:
  # git_tag:
  # slack:
  # slack_tag:

workflows:
  test_pipeline:
    jobs:
      - lint