version: 2.1
orbs:
  slack: circleci/slack@4.1.3
jobs:
  terraform_lint:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: cp providers.tf.example providers.tf
      - run: terraform-0.12.29 init
      - run: terraform-0.12.29 fmt -check=true
      - run: terraform-0.12.29 validate -var "deployment_id=validate" -var "route53_domain=validate-fake.com" -var "admin_email=fake@mailinator.com"
      - run: |
            for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cp providers.tf $example
            cd $example
            echo $example
            terraform-0.12.29 init
            terraform-0.12.29 fmt -check=true
            terraform-0.12.29 validate -var "deployment_id=citest"
            cd -
            done
      - run: terraform-0.12.29 -v
      - slack/notify:
          event: fail
          template: basic_fail_1

  terraform_apply:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            mv ./aws-iam-authenticator /usr/local/bin/
            which aws-iam-authenticator
      - run: EXAMPLE=from_scratch pipeline/run_terraform.sh
      - slack/notify:
          event: fail
          template: basic_fail_1

  terraform_destroy:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: DESTROY=1 EXAMPLE=from_scratch pipeline/run_terraform.sh
      - slack/notify:
          event: fail
          template: basic_fail_1
          
  git_tag:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: git remote set-url origin "https://astro-astronomer:${GITHUB_TOKEN}@github.com/astronomer/${CIRCLE_PROJECT_REPONAME}.git"
      - run: git tag 1.2.<< pipeline.number >>
      - run: git push origin << pipeline.git.branch >> --tags
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          custom: |
            {
              "text": "",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Deployment Successful! :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*:\\n$CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When*:\\n$(date +'%m/%d/%Y %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Tag*:\\n1.2.<< pipeline.number >>"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                    "alt_text": "CircleCI logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
      
      
workflows:
  test_pipeline:
    jobs:
      # - terraform_lint:
      #     context: slack
      # - terraform_apply:
      #     requires:
      #       - terraform_lint
      #     context: slack
      # - terraform_destroy:
      #     requires:
      #       - terraform_apply
      #     context: slack
      - git_tag:
          context:
            - github-repo
            - slack
          # requires:
          #   - terraform_destroy
          # filters:
          #   branches:
          #     only:
          #       - master
