version: 2.1
orbs:
  slack: circleci/slack@4.1.3
jobs:
  terraform_lint:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: apk add jq
      - run: cp providers.tf.example providers.tf
      - run: terraform-0.12.29 init
      - run: terraform-0.12.29 fmt -check=true
      - run: terraform-0.12.29 validate -var "deployment_id=validate" -var "route53_domain=validate-fake.com" -var "admin_email=fake@mailinator.com"
      - run: |
            for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cp providers.tf $example
            cd $example
            echo $example
            terraform-0.12.29 init
            terraform-0.12.29 fmt -check=true
            terraform-0.12.29 validate -var "deployment_id=citest"
            cd -
            done
      - run: terraform-0.12.29 -v
      - slack/notify:
          event: fail
          template: basic_fail_1

  terraform_apply:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: apk add jq
      - run: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            mv ./aws-iam-authenticator /usr/local/bin/
            which aws-iam-authenticator
      - run: EXAMPLE=from_scratch pipeline/run_terraform.sh
      - slack/notify:
          event: fail
          template: basic_fail_1

  terraform_destroy:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: apk add jq
      - run: DESTROY=1 EXAMPLE=from_scratch pipeline/run_terraform.sh
      - slack/notify:
          event: fail
          template: basic_fail_1
          
  git_tag:
    docker:
      - image: quay.io/astronomer/ci-terraform:2020-12
    steps:
      - checkout
      - run: apk add jq openssh
      - run: eval `ssh-agent`
      - add_ssh_keys:
          fingerprints:
            - "65:d4:19:be:6e:00:b2:8d:f3:03:47:22:76:1c:6f:b1"
      - run: git tag 1.1.<< pipeline.number >>
      - run: mkdir -p $HOME/.ssh
      - run: ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
      - run: git push git@github.com:astronomer/terraform-aws-astronomer-aws.git << pipeline.git.branch >> --tags
      
workflows:
  test_pipeline:
    jobs:
      - git_tag
      # - terraform_lint:
      #     context: slack
      # - terraform_apply:
      #     requires:
      #       - terraform_lint
      #     context: slack
      # - terraform_destroy:
      #     requires:
      #       - terraform_apply
      #     context: slack
      